server:
  port: 8060

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: post-api-gateway-service
  cloud:
    gateway:
      routes:
        - id: post-service
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
        - id: content-service
          uri: lb://content-service
          predicates:
            - Path=/api/auth/**, /api/content/**
  output:
    ansi:
      enabled: always


