version: '3.8'

services:
  # MySQL Database for content-service
  content-mysql:
    image: mysql:8.0
    container_name: content-mysql
    hostname: content-mysql  # Explicitly set hostname
    environment:
      #MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: content_db
      #MYSQL_USER: root
      #MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      #- ./content-data:/var/lib/mysql
      - ./src/main/resources/data/content.sql:/docker-entrypoint-initdb.d/content.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 30s
      retries: 10
      interval: 10s
      start_period: 90s  # Give MySQL more time for initial setup
    networks:
      - shared-network
  content-service:
    build: .
    container_name: content-service
    ports:
      - "8082:8082"
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://post-config-server:8088"
      SPRING_CLOUD_CONFIG_URI: http://post-config-server:8088
      SPRING_APPLICATION_NAME: content-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry-in-eureka:8761/eureka
      SPRING_DATASOURCE_URL: jdbc:mysql://content-mysql:3306/content_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      # JPA/Hibernate settings
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      content-mysql:
        condition: service_healthy

    networks:
      - shared-network
networks:
  shared-network:
    external: true
