#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: my-post-ingress
#spec:
#  ingressClassName: nginx
#  rules:
#    - http:
#        paths:
#          - pathType: Prefix
#            path: /
#            backend:
#              service:
#                name: my-react-post-app-service  # service name is used in reactJS to access the api
#                port:
#                  number: 80
