services:
  # Zipkin for distributed tracing
  zipkin-server:
    image: 'openzipkin/zipkin:latest'
    container_name: zipkin-server
    ports:
      - '9411:9411'
    #shared network is added
    networks:
      - shared-network
networks:
  shared-network:
    external: true


  #create a network, this is must
  #docker network create shared-network