version: '3.8'

services:
  post-api-gateway-service:
    build: .
    container_name: post-api-gateway-service
    ports:
      - "8060:8060"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://post-config-server:8088"
      SPRING_CLOUD_CONFIG_URI: http://post-config-server:8088
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry-in-eureka:8761/eureka

    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:
    external: true