apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-api-gateway-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: post-api-gateway-service-app
  template:
    metadata:
      labels:
        app: post-api-gateway-service-app
    spec:
      containers:
        - name: post-api-gateway-img
          image: explorejava/post-api-gateway-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8060
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://post-config-server:8088"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://post-config-server:8088"
#            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
#              value: "http://service-registry-in-eureka:8761/eureka/"
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Deureka.client.service-url.defaultZone=http://service-registry-in-eureka:8761/eureka/
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            # Tracing & Monitoring
            - name: MANAGEMENT_TRACING_ENABLED
              value: "true"
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: "http://zipkin-server:9411/api/v2/spans"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "health,info,prometheus"
      restartPolicy: Always # Equivalent to 'unless-stopped'

---
apiVersion: v1
kind: Service
metadata:
  name: post-api-gateway-service  # this service name will be used in ingress rule "my-ingress.yaml"
spec:
  type: ClusterIP
  selector:
    app: post-api-gateway-service-app
  ports:
    - protocol: TCP
      port: 8060
      targetPort: 8060