server:
  port: 8088
spring:
  profiles:
    active: git
  application:
    name: post-config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_REPO_URI:https://github.com/venkatram64/k8s-ms-cntralized-config.git}
          default-label: ${GIT_DEFAULT_BRANCH:main}
          search-paths:
            - config/{application}
#          search-paths:
#            - config/content-service/{application}
#            - config/post-service/{application}
#            - config/post-api-gateway-service/{application}
#            - config/service-registry-in-eureka/{application}
#            - config
          basedir: /tmp/config-repo
          force-pull: true
          clone-on-start: true
          timeout: 10
          refresh-rate: 30
          skip-ssl-validation: false  # Set to true only for testing with self-signed certs
      fail-fast: false
      retry:
        initial-interval: 3000
        max-attempts: 5
        max-interval: 10000
        multiplier: 1.2
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework.cloud.config.server.environment: TRACE
    org.eclipse.jgit: DEBUG