server:
  port: 8088

spring:  #config server configuration
  application:
    name: post-config-server
  instance:
    instance-id: ${spring.application.name}:${server.port}
  profiles:
    active: native
  output:
    ansi:
      enabled: always
