server:
  port: ${CONTENT_SERVICE_SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:  #for zipkin logging
    sampling:
      probability: 1.0

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_posts_new
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:  #database connection pool configuration
      connection-timeout: 15000
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 10000
      max-lifetime: 50000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always

eureka: #client is registering into Eureka server
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwtSecret: b6c3e9153b2ae05e5b20444bbf014ab0dba5cfac666117d767dbd284b825ed85
expirationInMs: 36000000