server:
  port: 8060

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      globalcors:  #cors(cross origin resource sharing) configuration
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
      routes:
        - id: post-service #micro service application name
          uri: lb://post-service #micro service application name
          predicates:
            - Path=/api/posts/**
        - id: content-service #micro service application name
          uri: lb://content-service #micro service application name
          predicates:
            - Path=/api/auth/**, /api/content/**, /api/users/**
  output:
    ansi:
      enabled: always