version: '3.8'

services:
  service-registry-in-eureka:
    build: .
    container_name: service-registry-in-eureka
    ports:
      - "8761:8761"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configserver:http://post-config-server:8088"
      SPRING_CLOUD_CONFIG_URI: http://post-config-server:8088
      SPRING_CLOUD_CONFIG_FAIL_FAST: false
      SPRING_CLOUD_CONFIG_RETRY_ENABLED: true
      SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS: 6
      SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL: 3000

      EUREKA_INSTANCE_HOSTNAME: service-registry-in-eureka
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:
    external: true

