apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-mysql-deploy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: content-mysql-db
  template:
    metadata:
      labels:
        app: content-mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "content_db"
            - name: MYSQL_ROOT_HOST
              value: "%"  # Allow root access from any host
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 30
            failureThreshold: 10
      volumes:
        - name: init-sql
          configMap:
            name: mysql-init-sql
      #restartPolicy: Always # Equivalent to 'unless-stopped'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-sql
data:
  content.sql: |
    CREATE DATABASE IF NOT EXISTS `content_db`;
    USE `content_db`;    
    CREATE TABLE IF NOT EXISTS `users` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `first_name` VARCHAR(50) NOT NULL,
    `last_name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(100) UNIQUE NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `role` VARCHAR(50) NOT NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `modified_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
    );
    

---
apiVersion: v1
kind: Service
metadata:
  name: content-mysql  # Service name used in content-service.yaml to access the MySQL database
spec:
  type: ClusterIP
  selector:
    app: content-mysql-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306