apiVersion: v1
kind: ConfigMap
metadata:
  name: dbconfigmap
data:
  posts_db_url: 'jdbc:mysql://mysql-db-instance.cnqqm04msin0.ap-south-1.rds.amazonaws.com:3306/posts_db'
  content_db_url: 'jdbc:mysql://mysql-db-instance.cnqqm04msin0.ap-south-1.rds.amazonaws.com:3306/content_db'
  post_service_url: 'https://k8s-kubesyst-myawsing-b2008b3270-663187801.ap-south-1.elb.amazonaws.com'  # alb dns name