apiVersion: v1
kind: ConfigMap
metadata:
  name: dbConfigmap
data:
  posts_db_url: 'jdbc:mysql://mysql-db-instance.cnqqm04msin0.ap-south-1.rds.amazonaws.com'
  content_db_url: 'jdbc:mysql://mysql-db-instance.cnqqm04msin0.ap-south-1.rds.amazonaws.com'
  post_service_url: 'https://259D9FF66EBAA551D4FE54366237D322.gr7.ap-south-1.eks.amazonaws.com'  # alb dns name