apiVersion: v1
kind: Secret
metadata:
  name: mysqlSecret
data:
  SPRING_DATASOURCE_USERNAME: YWRtaW4= # $ echo -n admin | base64
  SPRING_DATASOURCE_PASSWORD: YWRtaW4xMjM0IC1u #$ echo -n admin1234 | base64

