#logging you can turn off by commenting
#logging:
  #level:
    #org.springframework.security=TRACE
spring:
  application:
    name: content-service
  config:
    import: 'optional:configserver:http://post-config-server:8088'


