#logging you can turn off by commenting
#logging:
  #level:
    #org.springframework.security=TRACE

spring:
  application:
    name: content-service
  config:  #getting properties form config server
    import: "optional:configserver:http://localhost:8088"


